import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";

import FooterComponent from "./components/Footer";
import HeaderComponent from "./components/Header";

import { UserProvider } from "./context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>

          <HeaderComponent />
          <hr style={{ backgroundColor: "lightgray", border:"none", height: "2px",}} />
          <main>{children}</main>
          <FooterComponent />

        </UserProvider>
      </body>
    </html>
  )
};