import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import { UserProvider } from "./context/UserContext";

import FooterComponent from "./components/Footer";
import HeaderComponent from "./components/Header";

export const metadata: Metadata = {
  title: "Corpsoul Solutions",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body>
        <UserProvider>

          <HeaderComponent />
          <hr style={{ backgroundColor: "lightgray", border: "none", height: "2px", }} />
          <main>{children}</main>
          <FooterComponent />

        </UserProvider>
      </body>
    </html>
  )
};